id: I52C4CE99
legacy_id: P005444
ocr_import_info:
  bdrc_scan_id: W1KG4869
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T20:34:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:50:34.753456+00:00'
last_modified: 2022-09-01 00:50:41.457954
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4869
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4869
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྟོགས་པ་བརྗོད་པའི་ཚིགས་སུ་བཅད་པ་ཨུཏྤལའི་ཕྲེང་བ།
  author: ཞྭ་དམར ༠༤་པ་ཆོས་གྲགས་ཡེ་ཤེས།
statistics:
  ocr_word_mean_confidence_index: 0.7929491147554073
  ocr_word_median_confidence_index: 0.8700000047683716
quality: null
bases:
  I1KG4875:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4875
      total_pages: 106
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4875.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7929491147554073
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
