id: P005444
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:50:50.988465
source_metadata:
  id: bdr:W1KG4869
  title: རྟོགས་པ་བརྗོད་པའི་ཚིགས་སུ་བཅད་པ་ཨུཏྤལའི་ཕྲེང་བ་
  author: ''
  volumes:
    b772ea8db9684bf7b18f97e5debe525d:
      image_group_id: I1KG4875
      title: ''
      volume_number: 1
      total_pages: 106
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
