id: P005444
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4869
  title: རྟོགས་པ་བརྗོད་པའི་ཚིགས་སུ་བཅད་པ་ཨུཏྤལའི་ཕྲེང་བ་
  author: ''
  volumes:
    b772ea8db9684bf7b18f97e5debe525d:
      image_group_id: I1KG4875
      title: ''
      volume_number: 1
      total_pages: 106
